site_name: C# Snabbreferens
site_url: https://test.progdocs.se
theme:
  name: material
  font:
    text: Lato
    code: Source Code Pro
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: white
      accent: green
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: green
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details